# config
cover: https://mostro-complexity.github.io/image/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: '如果您同样热爱计算机、计算科学和音乐，请多多关注。'

# Content
excerpt_link: 阅读

# Miscellaneous
rss:
